<?php

namespace ContainerUN0FG7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HTD_2PtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hTD.2Pt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hTD.2Pt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\MixController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MixController::show' => ['privates', '.service_locator.IlfS6mK', 'get_ServiceLocator_IlfS6mKService', true],
            'App\\Controller\\MixController::vote' => ['privates', '.service_locator.7P9.byS', 'get_ServiceLocator_7P9_BySService', true],
            'App\\Controller\\VinylController::browse' => ['privates', '.service_locator.SN3hQvo', 'get_ServiceLocator_SN3hQvoService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MixController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MixController:show' => ['privates', '.service_locator.IlfS6mK', 'get_ServiceLocator_IlfS6mKService', true],
            'App\\Controller\\MixController:vote' => ['privates', '.service_locator.7P9.byS', 'get_ServiceLocator_7P9_BySService', true],
            'App\\Controller\\VinylController:browse' => ['privates', '.service_locator.SN3hQvo', 'get_ServiceLocator_SN3hQvoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MixController::new' => '?',
            'App\\Controller\\MixController::show' => '?',
            'App\\Controller\\MixController::vote' => '?',
            'App\\Controller\\VinylController::browse' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MixController:new' => '?',
            'App\\Controller\\MixController:show' => '?',
            'App\\Controller\\MixController:vote' => '?',
            'App\\Controller\\VinylController:browse' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
