<?php

namespace ContainerUN0FG7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IlfS6mKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IlfS6mK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IlfS6mK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mix' => ['privates', '.errored..service_locator.IlfS6mK.App\\Entity\\VinylMix', NULL, 'Cannot autowire service ".service_locator.IlfS6mK": it needs an instance of "App\\Entity\\VinylMix" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mix' => 'App\\Entity\\VinylMix',
        ]);
    }
}
