<?php

namespace ContainerUN0FG7j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_TwigRuntimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pagerfanta.twig_runtime' shared service.
     *
     * @return \Pagerfanta\Twig\Extension\PagerfantaRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'twig'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'PagerfantaRuntime.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'View'.\DIRECTORY_SEPARATOR.'ViewFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'babdev'.\DIRECTORY_SEPARATOR.'pagerfanta-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'View'.\DIRECTORY_SEPARATOR.'ContainerBackedImmutableViewFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'pagerfanta'.\DIRECTORY_SEPARATOR.'core'.\DIRECTORY_SEPARATOR.'RouteGenerator'.\DIRECTORY_SEPARATOR.'RouteGeneratorFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'babdev'.\DIRECTORY_SEPARATOR.'pagerfanta-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'RouteGenerator'.\DIRECTORY_SEPARATOR.'RequestAwareRouteGeneratorFactory.php';

        return $container->privates['pagerfanta.twig_runtime'] = new \Pagerfanta\Twig\Extension\PagerfantaRuntime('default', new \BabDev\PagerfantaBundle\View\ContainerBackedImmutableViewFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'default' => ['privates', 'pagerfanta.view.default', 'getPagerfanta_View_DefaultService', true],
            'foundation6' => ['privates', 'pagerfanta.view.foundation6', 'getPagerfanta_View_Foundation6Service', true],
            'semantic_ui' => ['privates', 'pagerfanta.view.semantic_ui', 'getPagerfanta_View_SemanticUiService', true],
            'twig' => ['privates', 'pagerfanta.view.twig', 'getPagerfanta_View_TwigService', true],
            'twitter_bootstrap' => ['privates', 'pagerfanta.view.twitter_bootstrap', 'getPagerfanta_View_TwitterBootstrapService', true],
            'twitter_bootstrap3' => ['privates', 'pagerfanta.view.twitter_bootstrap3', 'getPagerfanta_View_TwitterBootstrap3Service', true],
            'twitter_bootstrap4' => ['privates', 'pagerfanta.view.twitter_bootstrap4', 'getPagerfanta_View_TwitterBootstrap4Service', true],
            'twitter_bootstrap5' => ['privates', 'pagerfanta.view.twitter_bootstrap5', 'getPagerfanta_View_TwitterBootstrap5Service', true],
        ], [
            'default' => '?',
            'foundation6' => '?',
            'semantic_ui' => '?',
            'twig' => '?',
            'twitter_bootstrap' => '?',
            'twitter_bootstrap3' => '?',
            'twitter_bootstrap4' => '?',
            'twitter_bootstrap5' => '?',
        ]), ['default' => 'pagerfanta.view.default', 'foundation6' => 'pagerfanta.view.foundation6', 'semantic_ui' => 'pagerfanta.view.semantic_ui', 'twitter_bootstrap' => 'pagerfanta.view.twitter_bootstrap', 'twitter_bootstrap3' => 'pagerfanta.view.twitter_bootstrap3', 'twitter_bootstrap4' => 'pagerfanta.view.twitter_bootstrap4', 'twitter_bootstrap5' => 'pagerfanta.view.twitter_bootstrap5', 'twig' => 'pagerfanta.view.twig']), new \BabDev\PagerfantaBundle\RouteGenerator\RequestAwareRouteGeneratorFactory(($container->services['router'] ?? self::getRouterService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService'))));
    }
}
