<?php

namespace ContainerA9kfwLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SN3hQvoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SN3hQvo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SN3hQvo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mixRepository' => ['privates', 'App\\Repository\\VinylMixRepository', 'getVinylMixRepositoryService', true],
        ], [
            'mixRepository' => 'App\\Repository\\VinylMixRepository',
        ]);
    }
}
