<?php

namespace Container7LJR0FZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVinylMix2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IlfS6mK.App\Entity\VinylMix' shared service.
     *
     * @return \App\Entity\VinylMix
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IlfS6mK": it needs an instance of "App\\Entity\\VinylMix" but this type has been excluded in "config/services.yaml".');
    }
}
