<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMfHfbEO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMfHfbEO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMfHfbEO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMfHfbEO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMfHfbEO\App_KernelDevDebugContainer([
    'container.build_hash' => 'MfHfbEO',
    'container.build_id' => '86d4257c',
    'container.build_time' => 1715531620,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMfHfbEO');
