<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBv0uc3c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBv0uc3c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBv0uc3c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBv0uc3c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBv0uc3c\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bv0uc3c',
    'container.build_id' => 'c0fe827c',
    'container.build_time' => 1715552690,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBv0uc3c');
