<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIbmnp0T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIbmnp0T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIbmnp0T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIbmnp0T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIbmnp0T\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ibmnp0T',
    'container.build_id' => '4b8e1930',
    'container.build_time' => 1713740287,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIbmnp0T');
