<?php

namespace Container77juTVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVinylMixService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7P9.byS.App\Entity\VinylMix' shared service.
     *
     * @return \App\Entity\VinylMix
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7P9.byS": it needs an instance of "App\\Entity\\VinylMix" but this type has been excluded in "config/services.yaml".');
    }
}
